### ISSUE TITLE
Fov and show target problem

### ISSUE THREAD

**Issue by TRex9981e** [Averiias/Universal-SilentAim#39] opened 2023-04-04 00:25 UTC
in the script once you turn on fov or target it would be stuck on the left top corner of the screen and it been like this for awhile

**Comment by Chell-source** [comment] 2023-04-04 01:50
The problem is fixed now you need to try it again

**Comment by Averiias** [comment] 2023-04-04 06:04
Use the main.lua file

**Closed by Averiias** 2023-04-04 06:04 UTC
